
name: Checks

on:
  push:
    branches:
      - main

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Configure Docker CLI
        run: |
          echo '{"auths":{"docker.io":{"username": "'${{ secrets.DOCKERHUB_USER }}'", "password":"'${{ secrets.DOCKERHUB_TOKEN }}'", "email":"noreply@example.com","auth":"'$(echo -n ${{ secrets.DOCKERHUB_USER }}:${{ secrets.DOCKERHUB_TOKEN }} | base64)'"}}}' > /home/runner/work/_temp/.docker/config.json

      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"

      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"
